services:
  # --- Gateway (Entry Point) ---
  gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html/app:ro
    depends_on:
      - auth-service
      - ride-service

  # --- Databases & Cache ---
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ridestream_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # --- Message Broker (RabbitMQ) ---
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Communication port
      - "15672:15672" # Management UI (User: guest, Pass: guest)

  # --- Event Streaming (Kafka + Zookeeper) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- Microservices ---
  auth-service:
    build: ./services/auth-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ridestream_db
    depends_on:
      - postgres
    ports:
      - "3001:80"

  ride-service:
    build: ./services/ride-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ridestream_db
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3002-3005:80"

  location-service:
    build: ./services/location-service
    environment:
      - KAFKA_BROKER=kafka:29092
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - redis
    ports:
      - "3010:80"

  invoice-function:
    build: ./functions/invoice-function
    ports:
      - "5000:8080"

  # --- Email Testing Server ---
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP Port
      - "8025:8025" # Web UI
